### ISSUE TITLE
When rotating screen on DrinkDetailController the image doesn't resize to fill the screen

### ISSUE THREAD

**Issue by AndreasLengkeek** [uts-ios-dev/project3-43#2]

**Comment by AndreasLengkeek** [comment]
I think this may be related.
When the screen is rotated the drink images match the width but should try and fit height as well
![image](https://user-images.githubusercontent.com/10122406/40266745-ffc86616-5b93-11e8-9ce9-363c56dda057.png)

Also when you resize on the DrinkDetail View then it doesn't fix the space after the image.
![image](https://user-images.githubusercontent.com/10122406/40266753-166db24a-5b94-11e8-9bd0-29a0773d798f.png)

**Comment by AndreasLengkeek** [comment]
After some research online I found out that tinder is a 'portrait only' app. We should do the same thing to ours as well.

**Comment by JKumar1997** [comment]
Fixed to force vertical layout
